#!/bin/bash
rm ~/Android/AC100/kernel/*
cp arch/arm/boot/zImage ~/Android/AC100/kernel
for mod_ko in $(find ./ -name "*.ko")
do
cp $mod_ko ~/Android/AC100/kernel
done
arm-linux-gnueabi-strip --strip-debug ~/Android/AC100/kernel/*.ko
repack-bootimg.pl ~/Android/AC100/kernel/zImage ~/Android/AC100/6_LNX_raw.img-ramdisk.ext4 ~/Android/AC100/newkern.img

